# Generated by Django 5.1.2 on 2024-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='adm',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
